name: Run tests

on:
  push:
    paths:
      - '.github/**'
      - 'deps/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'examples/**'
      - 'python/**'
      - '.gitignore'
      - '.gitmodules'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  build_dir: "build"
  config: "Release"

jobs:
  test-with-pocl:
    runs-on:
      ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt update
          sudo ./deps/vortex/ci/install_dependencies.sh
      - name: Build Vortex with toolchain
        run: |
          python3 ./build_vortex.py
      - name: Build spla
        run: |
          python3 ./build.py --build-dir=${{ env.build_dir }} --vortex=YES --vortex-tooldir=${{ github.workspace }}/vortex-tools --vortex-dir=${{ github.workspace }}/deps/vortex/build
      - name: Run tests on vortex simx
        run: |
          source ./deps/vortex/build/ci/toolchain_env.sh
          ./deps/vortex/build/ci/blackbox.sh --driver=simx --app=opencl/copybuf
          ./deps/vortex/build/ci/blackbox.sh --driver=rtlsim --app=opencl/copybuf
          ./deps/vortex/build/ci/blackbox.sh --driver=opae --app=opencl/copybuf
          ./deps/vortex/build/ci/blackbox.sh --driver=xrt --app=opencl/copybuf
